name: test build project
on:
  push:
    branches:
      - 'master'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: setup libraries # raylib requires display headers
        run: sudo apt install -y libwayland-dev libxkbcommon-dev libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxxf86vm-dev
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: ./
          build-dir: "build"
          generator: Ninja
          cxx-compiler: clang++
          cxx-flags: "-Werror"
          options: |
            "CMAKE_BUILD_TYPE=Release"
            "GLFW_BUILD_X11=ON"
            "GLFW_BUILD_WAYLAND=ON"
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: ./
          build-dir: "build"
          generator: Ninja
          options: |
            "CMAKE_BUILD_TYPE=Release"
            "LINK_OPTIONS=/W4"
